### ISSUE TITLE
Error Trying to Install DRV2605

### ISSUE THREAD

**Issue by ErinC13** [KenT2/pipresents-kms#14]
I'm following the instructions to install KMS on my Raspberry Pi 4 model B. I used this command python3 -m pip install DRV2605 and I got the error below

valak13@raspberrypi:~ $ python3 -m pip install DRV2605
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    For more information visit http://rptl.io/venv

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.

I also tried to put the command in the format the error above mentions; pt install python3-xyz

valak13@raspberrypi:~ $ apt install python3-DRV2605
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?

iIm sure this is user error, but I've been trying to figure this out for over an hour. Any help is appreciated!

**Comment by KenT2** [comment]
It looks like you are using RPI OS Bookworm. For pp-KMS you need to use Bullseye 32 bit.

**Comment by ErinC13** [comment]
I went back and used Bullseye 32 bit and got it working. Thanks!
