### ISSUE TITLE
ModuleNotFoundError: No module named 'selenium.webdriver.common.fedcm'

### ISSUE THREAD

**Issue by fernando-pfsense** [KenT2/pipresents-kms#18]
I installed pipresents using the readme, however when i run `python3 /home/<username>/pipresents/pipresents.py` i get this error: `ModuleNotFoundError: No module named 'selenium.webdriver.common.fedcm'`

**Comment by KenT2** [comment]
I suspect you have forgotten to install one of the these two modules
    sudo pip3 install selenium
    sudo apt install chromium-chromedriver

**Comment by fernando-pfsense** [comment]
I suspected the same as well, so i ran both again, but no change

**Comment by KenT2** [comment]
OK, in that case I suspect that pip is installing a recent version of selenium which is broken. Could you do the following and post the result
pip show selenium
apt show python3-selenium

I expect apt to show version 4.0.0~a1+dfsg1-1.1 and pip to show version 4.27.1 or something similar.

I have not tried this so do not do it on an important SD card but I you do
     sudo pip uninstall selenium
  you should revert to the older apt version which hopefully will work.

**Comment by fernando-pfsense** [comment]
Ok here are the results of the 2 commands

`$ pip show selenium
Name: selenium
Version: 4.27.1
Summary: Official Python bindings for Selenium WebDriver.
Home-page: None
Author: None
Author-email: None
License: Apache 2.0
Location: /usr/local/lib/python3.9/dist-packages
Requires: certifi, trio, websocket-client, typing-extensions, urllib3, trio-websocket
Required-by: `

`$ apt show python3-selenium
Package: python3-selenium
Version: 4.0.0~a1+dfsg1-1.1
Priority: optional
Section: python
Source: python-selenium
Maintainer: Sascha Girrulat <sascha@girrulat.de>
Installed-Size: 588 kB
Depends: python3-urllib3, python3:any
Recommends: chromium-driver | chromedriver | phantomjs
Homepage: http://www.seleniumhq.org
Download-Size: 97.4 kB
APT-Sources: http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages
Description: Python3 bindings for Selenium
 Python3 language bindings for Selenium WebDriver.
 .
 The `selenium` package is used automate web browser interaction from Python.
 Several browsers/drivers are supported (Firefox, Chrome, Internet Explorer,
 PhantomJS), as well as the Remote protocol.
 .
 The webdriver parts itself are not included in this package.`

I tried to uninstall then i just get this error: `ModuleNotFoundError: No module named 'selenium'`

Figured maybe the chrome driver isn't there, but when i reinstall i get this `chromium-chromedriver is already the newest version (126.0.6478.164-rpt1).`

**Comment by fernando-pfsense** [comment]
I tried to uninstall selenium as you suggested, then i just get this error: `ModuleNotFoundError: No module named 'selenium'`

Figured maybe the chrome driver isn't there, but when i reinstall i get this `chromium-chromedriver is already the newest version (126.0.6478.164-rpt1).`

**Comment by KenT2** [comment]
Yes, you do have a very recent version of selenium
I thought removing the pip version would revert to the apt version but it seems it does not.
Can you install an old pip version of selenium using the command
sudo pip install selenium==4.0.0a1

That should get you back to the version that I have here.

**Comment by fernando-pfsense** [comment]
this worked.

**Comment by KenT2** [comment]
That's good, its been a useful exercise to understand pip and apt. I have just updated github to version 1.5.3f  of pp-kms which removes the need for pip. You do not need to update your installation
