### ISSUE TITLE
mpv player crashes if no audio in mp4 file

### ISSUE THREAD

**Issue by VizDock** [KenT2/pipresents-kms#3]
mp4 file created with powerpoint (save as mp4) doesn't have audio track at all. When added to show, player crashes. If audio is added in powerpoint presentation, it plays OK.
mpv player plays same mp4 file normally, outside pi presents.
Couldn't figure out the reason
In older version of pi presents it worked. (cant remember which version we had installed before pi crashed because of SD card issue)

**Comment by KenT2** [comment]
I do not have a Powerpoint that creates mp4's, could you provide an example of the No Sound
I have changed videoplayer to mpv. Earlier versions used omxplayer

**Comment by VizDock** [comment]
Hi
Here you go

https://github.com/KenT2/pipresents-kms/assets/7253109/1618e1eb-de7b-4836-b858-6d4dee0bfebc


https://github.com/KenT2/pipresents-kms/assets/7253109/a2abc378-c4c5-4a3d-854c-1fb7a237ad92

**Comment by KenT2** [comment]
Thanks for the videos. It affected other silent videos so not just a Powerpoint problem. I have fixed the problem in version 1.5.3c which is now on Github.

**Comment by VizDock** [comment]
Thanks
