### ISSUE TITLE
autostart does not allow debugging mode

### ISSUE THREAD

**Issue by petersont4** [KenT2/pipresents-kms#4]
I am trying to enable debug level 128 on PiPresents autostart, but when I add --debug 128 to the autostart options, the information I except to see does not appear in the logs.  When I put --debug 128 into the Manager start options, everything works as expected when I start the show from the web portal.

**Comment by KenT2** [comment]
Tried it here and it seems to work OK. The line I added to autostart for a username of pp was 

/usr/bin/python3 /home/pp/pipresents-kms/pipresents.py -o /home/pp -p 1p5_examples/pp_mediashow_1p5 -d 128
