### ISSUE TITLE
Video playback error

### ISSUE THREAD

**Issue by reflexsa** [KenT2/pipresents-kms#5]
Firstly, thank you for pipresents. I have just recently started using it and so far looks like a versatile piece of software.
I'm having a few issues (probably user related). 
Hardware: Pi3B+
OS and pipresents version: I re-installed yesterday following the guide.
Initially I had not set the GPU memory, and I'm attempting to play 1080p60 videos. The video would play but not smoothly.
I increased the GPU memory to 256mb after some reading, however when it attempts to play the video I receive a "MPVDriver" error:
"System Error: load failed due to timeout load position is:-1"

I did see that MPV only uses CPU, is there a way to make use of the GPU? Previously I had these videos running on the same hardware using ScreenlyOSE. While Screenly worked pipresents has great interactive features that I would like to make use of.

Thank you for any assistance.

**Comment by KenT2** [comment]
You do not need to increase GPU memory with pipresents-kms. IIRC this was required only for omxplayer. I expect the timeout error was due to running out of RAM but if it persists with 76M of gpumem then tell me.

Unfortunately I cannot find any way to make mpv be hardware accelerated. I've been googling it for months.

**Comment by reflexsa** [comment]
Thanks, I'm actually going to try a different memory card, I suspect the one I have in there is not the best.

**Comment by reflexsa** [comment]
Setting memory back to 76M did solve the timeout issue. I will experiment with alternative resolutions and framerates to see if I can get smooth playback on Pi3. Thank you.

**Comment by reflexsa** [comment]
Just an update. Running a Pi4 with a decent sdcard worked acceptably at 1080p 25fps. I am yet to try the same sdcard on the Pi3.

**Comment by KenT2** [comment]
Interesting about the SD card making a difference. CPU speed of the 2 are similar so it might work OK.
