### ISSUE TITLE
Profile error with all profiles

### ISSUE THREAD

**Issue by vicdemuth** [KenT2/pipresents-kms#6]
Hi Ken,

Just trying the new version and getting this error:  

A/V is not supported by Pi Presents
Use a HDMI to PAL/NTSC convertor

Any suggestions?

Rgds

Vic

**Comment by KenT2** [comment]
With the change of RPi OS to DRM/KMS it has become increasingly difficult to use the A/V video output, the A/V jack has been removed on Pi5. Instead you can purchase a HDMI to PAL/NTSC convertor which you plug into a HDMI lead. They are not expensive on Amazon.
I'm surprised you got the message on all profiles unless you are moving from an earlier version of PP and that is what you used

**Comment by vicdemuth** [comment]
Hi Ken,
Apologies. Turns out it was a faulty SD card. Go figure :)
Anyway, just as an aside, I've noticed a typo in the examples.sh script with the path to the profile folder being incorrect. Not in and of itself a real problem, just thought you would like to know.
