### ISSUE TITLE
python-mpv requires libmpv with an API version of 1.108 or higher (libmpv >= 0.33), but you have an older version (1.107).

### ISSUE THREAD

**Issue by jochenlaser** [KenT2/pipresents-kms#8]
I am trying to install pipresents   KenT2-pipresents-kms-1c20785 

on a Raspberry Pi 3B+, running Bullseye:

Raspberry Pi OS (Legacy) with desktop
Release date: December 5th 2023
System: 64-bit
Kernel version: 6.1
Debian version: 11 (bullseye)

As I understand that is the right combination for the beta version

I also installed the various dependencies:
=== snip ===
   sudo apt install python3-pil.imagetk
     sudo apt install unclutter
     sudo apt install mplayer

     sudo pip3 install selenium
     sudo apt install chromium-chromedriver

     sudo apt install mpv
     sudo apt install python3-mpv
     python3 -m pip install DRV2605

=== snap ===

As far as I can make out, the libmpv comes with python3-mpv  
But when starting one of the examples, I get the above error:

python-mpv requires libmpv with an API version of 1.108 or higher (libmpv >= 0.33), but you have an older version (1.107).

I can think of various ad-hoc fixes for this issues, 
and it might be it's an issue in the python3-mpv package rather that PiPresents,
but I guess it might be appropriate  to report this as a beta tester

**Comment by KenT2** [comment]
Thanks for the useful report which I need to something about. It seems to me to be a compatibility issue between mpv and python-mpv both obtained from apt which I assumend would not be possible. I notice that PyPi has mpv and python-mpv both at 1.105 which would be worth a try.

I haven't had compatibiltiy problems before so I'm struggling with a solution (as well as a bad cold), what would be your solution?

**Comment by KenT2** [comment]
Just tried installing pp_KMS on the latest issue of bullseye legacy (5 Dec 23) per instructions. All works fine.
Looking at your report you are using 64bit Pi OS whereas I was using 32 bit. Think that could be the problem.

**Comment by jochenlaser** [comment]
Ooops, I'll give it another try! Thanks for pointing out where I went wrong!

**Comment by jochenlaser** [comment]
You are right. Works like a charm now. Thank you!

**Comment by KenT2** [comment]
That's good. Good lesson for me. I was thinking of moving PP to 64 bit but I'm going to have to be careful with availability of compatible libraries.
