### ISSUE TITLE
pip install failing when following README

### ISSUE THREAD

**Issue by smarques** [KenT2/pipresents-kms#9]
Hi, I try to follow the README file, but:
(using: latest bookworm)

`sudo pip3 install selenium`
gives me
```
This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.

If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.

    For more information visit http://rptl.io/venv
```

So I created a venv and activated it
then
`python3 -m pip install selenium.  #works!!`
but
`python3 -m pip install chromium-chromedriver`
fails with 

```
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
ERROR: Could not find a version that satisfies the requirement chromium-chromedriver (from versions: none)
ERROR: No matching distribution found for chromium-chromedriver
```

**Comment by KenT2** [comment]
The readme says use Bullseye. 

The code of KMS probably works on Bookworm provided you switch from Wayland to X. However as you found there are problems with virtual environments. I gave up with KMS on Bookworm X which is a dead end and am busy converting the code to run under Wayland. This involves code changes throughout to replace Tkinter and Pillow with Gtk4. I do have a nearly working system but it will be a few months before I issue Version 1.6   - pipresents-Gtk

**Comment by smarques** [comment]
You are right sorry I missed that
